### ISSUE TITLE
Missing plugin model on published packages

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.experimental#22]
**Problem Description**
Taking as exemple the plugin `miat.gama.extension.qrcode`, in the repository's source file, there is a gama project ( https://github.com/gama-platform/gama.experimental/tree/GAMA_1.8.2/miat.gama.extension.qrcode/models/QR%20code ) made to be imported in the Plugin folder once installed.

Unfortunatly, the compilation may remove this folder and is missing from the online compiled version (the version downloadable from within GAMA). :/

**Expected Behavior**
Having the gama project in the jar compiled plugin available online.

**Comment by hqnghi88** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/6105384/174709944-249ca47b-0255-4432-972d-a350f8a2115b.png">
because it is not checked in binray build
