### ISSUE TITLE
UML plugin is not working anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.experimental#26]
after installing the UML plugin on the latest GAMA 1.9.0, I cannot convert any model to UML, I have the following error:
```
An internal error occurred during: "Converting to UML".
class java.util.LinkedHashMap cannot be cast to class java.util.Iterator (java.util.LinkedHashMap and java.util.Iterator are in module java.base of loader 'bootstrap')
```

**Comment by benoitgaudou** [comment]
I fix the bug. Nevetheless, even if a file is generated, it is in the Papyrus Eclipse UML format, not so easy to manipulate...
